Fixed flow in build process

diff --git a/scripts/flow b/scripts/flow
--- a/scripts/flow
+++ b/scripts/flow
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 # Copyright (c) 2016-2017 Martin Donath <martin.donath@squidfunk.com>
 
 # Permission is hereby granted, free of charge, to any person obtaining a copy
@@ -18,14 +20,25 @@
 # FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 # IN THE SOFTWARE.
 
-# Files generated by build
-/build
-/material
-/site
+# Check if "npm install" was executed
+if [[ ! -d `npm bin` ]]; then
+  echo "\"node_modules\" not found:"
+  echo "npm install"
+  exit 1
+fi
 
-# Files generated by flow typechecker
-/tmp
+# Annotate source files
+`npm bin`/gulp assets:javascripts:annotate "$@"
+FLOW_JSDOC=$?
 
-# Files generated by visual tests
-/gemini-report
-/tests/visual/data
+# Run flow typecheck
+`npm bin`/flow check tmp
+FLOW=$?
+
+# If one command failed, exit with error
+if [ $FLOW_JSDOC -gt 0 ] || [ $FLOW -gt 0 ]; then
+  exit 1
+fi;
+
+# Otherwise return with success
+exit 0
