Updated snapshot tests

diff --git a/scripts/help b/scripts/help
--- a/scripts/help
+++ b/scripts/help
@@ -20,12 +20,8 @@
 # FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 # IN THE SOFTWARE.
 
-# Check if "yarn install" was executed
-if [[ ! -d "$(yarn bin)" ]]; then
-  echo "\"node_modules\" not found:"
-  echo "yarn install"
-  exit 1
-fi
+# Exit, if one command fails
+set -e
 
-# Run command
-"$(yarn bin)"/gulp help "@"
+# Show usage and help message
+"$(npm bin)"/gulp help "$@"
diff --git a/scripts/lint b/scripts/lint
--- a/scripts/lint
+++ b/scripts/lint
@@ -20,25 +20,11 @@
 # FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 # IN THE SOFTWARE.
 
-# Check if "yarn install" was executed
-if [[ ! -d "$(yarn bin)" ]]; then
-  echo "\"node_modules\" not found:"
-  echo "yarn install"
-  exit 1
-fi
+# Exit, if one command fails
+set -e
 
 # Run ESLint
-"$(yarn bin)"/eslint --max-warnings 0 .
-ESLINT=$?
+"$(npm bin)"/eslint --max-warnings 0 .
 
 # Run Stylelint
-"$(yarn bin)"/stylelint `find src/assets -name *.scss`
-STYLELINT=$?
-
-# If one command failed, exit with error
-if [ $ESLINT -gt 0 ] || [ $STYLELINT -gt 0 ]; then
-  exit 1
-fi;
-
-# Otherwise return with success
-exit 0
+"$(npm bin)"/stylelint `find src/assets -name *.scss`
diff --git a/scripts/start b/scripts/start
--- a/scripts/start
+++ b/scripts/start
@@ -20,13 +20,9 @@
 # FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 # IN THE SOFTWARE.
 
-# Check if "yarn install" was executed
-if [[ ! -d "$(yarn bin)" ]]; then
-  echo "\"node_modules\" not found:"
-  echo "yarn install"
-  exit 1
-fi
+# Exit, if one command fails
+set -e
 
-# Run command
-"$(yarn bin)"/gulp clean && \
-"$(yarn bin)"/gulp watch --no-lint "$@"
+# Watch for changes and rebuild assets on the fly
+"$(npm bin)"/gulp clean
+"$(npm bin)"/gulp watch --no-lint "$@"
diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -20,13 +20,9 @@
 # FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 # IN THE SOFTWARE.
 
-# Check if "yarn install" was executed
-if [[ ! -d "$(yarn bin)" ]]; then
-  echo "\"node_modules\" not found:"
-  echo "yarn install"
-  exit 1
-fi
+# Exit, if one command fails
+set -e
 
-# Run command
-"$(yarn bin)"/gulp tests:snapshot:generate
-"$(yarn bin)"/karma start tests/karma.conf.js --single-run
+# Generate fixtures and run snapshot tests
+"$(npm bin)"/gulp tests:snapshot:generate
+"$(npm bin)"/karma start tests/karma.conf.js --single-run "$@"
